{
    "_Type": "Action.Type.ODataService.DraftEnabled.Edit",
    "Target": {
        "Service": "/riskmobileapp/Services/riskmanagement1Service.service",
        "EntitySet": "Mitigations",
        "ReadLink": "{@odata.readLink}"
    },
    "ShowActivityIndicator": true,
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": {
        "Name": "/riskmobileapp/Actions/UpdateEntitySuccessMessage.action",
        "Properties": {
            "Message": "Draft Edit"
        }
    },
    "OnFailure": "/riskmobileapp/Actions/UpdateEntityFailureMessage.action"
}